sudo: required
language: ruby
cache: bundler
rvm:
  - "1.9.3-p551"
services:
  - mongodb
bundler_args: --without development debug
before_script:
  - export TZ=America/Sao_Paulo
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database redu_test;'
  - bundle exec rake db:schema:load RAILS_ENV=test
env:
  - TEST_SUITE=abilities
  - TEST_SUITE=adapters
  - TEST_SUITE=controllers
  - TEST_SUITE=helpers
  - TEST_SUITE=jobs
  - TEST_SUITE=libs
  - TEST_SUITE=mailers
  - TEST_SUITE=models
  - TEST_SUITE=observers
  - TEST_SUITE=representers
  - TEST_SUITE=services
  - TEST_SUITE=views
  - TEST_SUITE=visualizations
script: "bundle exec rspec spec/$TEST_SUITE"
before_install:
  - chmod +x ./script/grant_travis_privileges_on_mysql.sh
  - ./script/grant_travis_privileges_on_mysql.sh
