meta_description: 'A description of your community for use in META tags.'
meta_keywords: 'keywords for use in META tags'
robots_meta_list_content: 'noindex,follow'
robots_meta_show_content: 'index,nofollow'

# Comment this out if you want to infer the locale
# off of the http headers
community_locale: "pt-BR"

# The label you use for 'staff' writers (featured writer, staff, pro, etc.)
require_captcha_on_signup: false

# setup
closed_beta_mode: false
show_constellation: false
activate_payment: false
show_advertising: false

users_per_page: 10
attachments_number: 6
moderate: ['Exam', 'InteractiveClass', 'Seminar']

points:
  created_lecture: 80
  updated_lecture: 15
  show_lecture: 10
  created_exam: 40
  updated_exam: 15
  show_exam: 10
  answer_exam: 20
  created_resource: 30
  show_resource: 15


reserved_logins: [
  'about',
  'account',
  'admin',
  'advertise',
  'ads',
  'application',
  'assets',
  'access_keys',
  'beta_keys',
  'beta',
  'blog',
  'categories',
  'choices',
  'clippings',
  'clipping_images',
  'comments',
  'contests',
  'countries',
  'credits',
  'css_help',
  'events',
  'exams',
  'exames',
  'faq',
  'featured',
  'forums',
  'friendships',
  'friendship_statuses',
  'home',
  'homepage_features',
  'images',
  'invitations',
  'javascripts',
  'login',
  'logout',
  'lessons',
  'manage_photos',
  'messages',
  'metro_areas',
  'moderatorships',
  'new_clipping',
  'offerings',
  'photos',
  'polls',
  'popular',
  'popular_rss',
  'posts',
  'recent',
  'redu',
  'resources',
  'roles',
  'search',
  'seminars',
  'seminarios',
  'signup',
  'sb_posts',
  'spaces',
  'skills',
  'sitemap',
  'states',
  'stylesheets',
  'tags',
  'theme',
  'topics',
  'users',
  'votes']
