<% config = Redu::Application.config.s3_config['defaults'] %>

defaults: &defaults
  fog_provider: 'AWS'
  aws_access_key_id: "<%= config['access_key_id'] %>"
  aws_secret_access_key: "<%= config['secret_access_key'] %>"
  fog_directory: "redu-assets-staging"
  # You may need to specify what region your storage bucket is in
  # fog_region: "eu-west-1"
  # To delete existing remote files.
  existing_remote_files: delete
  # Automatically replace files with their equivalent gzip compressed version
  gzip_compression: true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently: true

development:
  <<: *defaults
  enabled: false

test:
  <<: *defaults
  enabled: false

staging:
  <<: *defaults

production:
  <<: *defaults
  fog_directory: "redu-assets2"
