embed_assets: on
s3_cache_control: 432000
s3_access_key_id: AKIAIRKVQDTWT2NN4J4Q
s3_secret_access_key: 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
s3_permission: public_read
s3_bucket: redu-assets-staging
s3_upload_files:
  - public/images/new/**
  - public/javascripts/**
  - public/javascripts/ckeditor/**/**/**/*
  - public/stylesheets/**

javascripts:
  common:
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/modernizr.js
    - public/javascripts/jquery.tipTip.minified.js
    - public/javascripts/folders.js
    - public/javascripts/exercise.js
    - public/javascripts/lectures.js
    - public/javascripts/swfobject.js
    - public/javascripts/jquery.form.js
    - public/javascripts/jquery.remotipart.js
    - public/javascripts/lazyload.js
    - public/javascripts/jquery.fcbkcomplete.min.js
    - public/javascripts/jquery.tokeninput.js
    - public/javascripts/jquery.filestyle.mini.js
    - public/javascripts/form.redu.jquery.js
    - public/javascripts/asyncjs.jquery.js
    - public/javascripts/user.js
    - public/javascripts/browserdetection.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/ytpreview.jquery.js
    - public/javascripts/subjects.js
    - public/javascripts/statuses.js
    - public/javascripts/admin.js
    - public/javascripts/jquery.nested-fields.js
  chat:
    - public/javascripts/jquery.pjax.js
    - public/javascripts/pusher.js
    - public/javascripts/jquery.json.js
    - public/javascripts/jquery.linkify-1.0.js
    - public/javascripts/chat.jquery.js
    - public/javascripts/chat.js
  ie:
    - public/javascripts/json2.js
    - public/javascripts/selectivizr.js
  user:
    - public/javascripts/jquery.maskedinput.js
  ckeditor:
    - public/javascripts/ckeditor/ckeditor.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/960.css
    - public/stylesheets/new-fonts.css
    - public/stylesheets/new-style.css
    - public/stylesheets/tipTip.css
    - public/stylesheets/ajaxful_rating.css
    - public/stylesheets/fb_style.css
    - public/stylesheets/token-input.css
    - public/stylesheets/form.redu.css
    - public/stylesheets/table.redu.css
    - public/stylesheets/icons.big.redu.css
    - public/stylesheets/icons.redu.css
    - public/stylesheets/user.css
    - public/stylesheets/exercise.css
  ie:
    - public/stylesheets/ie.css
  chat:
    - public/stylesheets/chat.css
