development:
  adapter: mysql2
  username: root
  password:
  database: redu_development
  host: db

production:
  adapter: mysql2
  username: root
  password:
  database: redu_production
  host: db

performance:
  adapter: mysql2
  username: root
  password:
  database: redu_performance
  host: db

staging:
  adapter: mysql2
  username: root
  password:
  database: redu_staging
  host: db

test:
  adapter: mysql2
  username: root
  password:
  database: redu_test
  host: db
