defaults: &defaults
  access_key_id: AKIAIRKVQDTWT2NN4J4Q
  secret_access_key: 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

staging: &staging
  <<: *defaults
  bucket: redu-uploads-staging
  videos_bucket: redu-uploads-staging
  files_bucket: redu-uploads-staging
  assets_bucket: redu-assets-staging

production:
  <<: *defaults
  bucket: redu_uploads
  videos_bucket: redu-videos
  files_bucket: redu_files
  assets_bucket: redu-assets

development:
  <<: *defaults

performance:
  <<: *defaults

test:
  <<: *defaults
