production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: solr
    port: 8982
    log_level: INFO

staging:
  solr:
    hostname: solr
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: solr
    port: 8981
    log_level: WARNING

