pt-BR:
    administrator: "administracao"
    activate: "ativar"
    admin_members: "admin_membros"
    admin_requests: "admin_solicitacoes"
    answer: "responder"
    bulletins: "noticias"
    lectures: "aulas"
    contact: "contato"
    edit: "editar"
    enroll: "inscrever"
    events: "eventos"
    exams: "exames"
    favorites: "favoritos"
    folders: "arquivos"
    invite: "convidar"
    environment_invitations: "convite"
    join: "entrar"
    learn: "aprenda"
    look_and_feel: "aparencia"
    manage: "gerenciar"
    member: "membro"
    members: "membros"
    moderate: "moderacao"
    new: "criar"
    owner: "dono"
    results: "resultados"
    questions: "questao"
    choices: "escolhas"
    spaces: "espacos"
    courses: "cursos"
    show_favorites: "favoritos"
    signup: "registrar"
    subjects: "modulos"
    #submissions : "submiss√µes"
    teach: "ensine"
    unjoin: "abandonar"
    users: "pessoas"
    user_course_invitations: "convites"
    environments: "ambientes"
    accept: "aceita"
    decline: "rejeita"
    friendships: "amigos"
    pending: "pendentes"
    invoices: "faturas"
    plans: "planos"
    admin_invitations: "administrar_convites"
    invite_members: "convidar_membros"
    partners: "parceiros"
    partner_environment_associations: "clientes"
    partner_user_associations: "colaboradores"
    my_wall: "meu_mural"
